Apply changes from upstream ejabberd 24.07

diff --git a/ecs/bin/ejabberdctl b/ecs/bin/ejabberdctl
--- a/ecs/bin/ejabberdctl
+++ b/ecs/bin/ejabberdctl
@@ -2,7 +2,6 @@
 
 # define default configuration
 POLL=true
-SMP=enable
 ERL_MAX_PORTS=32000
 ERL_PROCESSES=250000
 ERL_MAX_ETS_TABLES=1400
@@ -95,9 +94,12 @@ ERL_CRASH_DUMP="$LOGS_DIR"/erl_crash_$(date "+%Y%m%d-%H%M%S").dump
 ERL_INETRC="$ETC_DIR"/inetrc
 
 # define ejabberd parameters
-EJABBERD_OPTS="$EJABBERD_OPTS\
-$(sed '/^log_rotate_size/!d;s/:[ \t]*\([0-9]\{1,\}\).*/ \1/;s/:[ \t]*\(infinity\).*/ \1/;s/^/ /' "$EJABBERD_CONFIG_PATH")\
-$(sed '/^log_rotate_count/!d;s/:[ \t]*\([0-9]*\).*/ \1/;s/^/ /' "$EJABBERD_CONFIG_PATH")"
+EJABBERD_OPTS="\
+$(sed '/^log_rotate_size/!d;s/:[ \t]*\([0-9]\{1,\}\).*/ \1/;s/:[ \t]*\(infinity\).*/ \1 /;s/^/ /' "$EJABBERD_CONFIG_PATH")\
+$(sed '/^log_rotate_count/!d;s/:[ \t]*\([0-9]*\).*/ \1 /;s/^/ /' "$EJABBERD_CONFIG_PATH")\
+$(sed '/^log_burst_limit_count/!d;s/:[ \t]*\([0-9]*\).*/ \1 /;s/^/ /' "$EJABBERD_CONFIG_PATH")\
+$(sed '/^log_burst_limit_window_time/!d;s/:[ \t]*\([0-9]*[a-z]*\).*/ \1 /;s/^/ /' "$EJABBERD_CONFIG_PATH")\
+$EJABBERD_OPTS"
 [ -n "$EJABBERD_OPTS" ] && EJABBERD_OPTS="-ejabberd $EJABBERD_OPTS"
 EJABBERD_OPTS="-mnesia dir \"$SPOOL_DIR\" $MNESIA_OPTIONS $EJABBERD_OPTS -s ejabberd"
 
@@ -148,14 +150,6 @@ exec_iex()
 # usage
 debugwarning()
 {
-    if [ "$OSTYPE" != "cygwin" ] && [ "$OSTYPE" != "win32" ] ; then
-        if [ "a$TERM" = "a" ] || [ "$TERM" = "dumb" ] ; then
-            echo "Terminal type not supported."
-            echo "You may have to set the TERM environment variable to fix this."
-            exit 8
-        fi
-    fi
-
     if [ "$EJABBERD_BYPASS_WARNINGS" != "true" ] ; then
         echo "--------------------------------------------------------------------"
         echo ""
@@ -169,11 +163,13 @@ debugwarning()
         echo "To exit and detach this shell from ejabberd, press:"
         echo "  control+g and then q"
         echo ""
+        #vt100 echo "Please do NOT use control+c in this debug shell !"
+        #vt100 echo ""
         echo "--------------------------------------------------------------------"
         echo "To bypass permanently this warning, add to ejabberdctl.cfg the line:"
         echo "  EJABBERD_BYPASS_WARNINGS=true"
         echo "Press return to continue"
-        read -r input
+        read -r _
         echo ""
     fi
 }
@@ -196,8 +192,41 @@ livewarning()
         echo "To bypass permanently this warning, add to ejabberdctl.cfg the line:"
         echo "  EJABBERD_BYPASS_WARNINGS=true"
         echo "Press return to continue"
-        read -r input
+        read -r _
         echo ""
+    fi
+}
+
+check_etop_result()
+{
+    result=$?
+    if [ $result -eq 1 ] ; then
+        echo ""
+        echo "It seems there was some problem running 'ejabberdctl etop'."
+        echo "Is the error message something like this?"
+        echo "  Failed to load module 'etop' because it cannot be found..."
+        echo "Then probably ejabberd was compiled with development tools disabled."
+        echo "To use 'etop', recompile ejabberd with: ./configure --enable-tools"
+        echo ""
+        exit $result
+    fi
+}
+
+check_iex_result()
+{
+    result=$?
+    if [ $result -eq 127 ] ; then
+        echo ""
+        echo "It seems there was some problem finding 'iex' binary from Elixir."
+        echo "Probably ejabberd was compiled with Rebar3 and Elixir disabled, like:"
+        echo "  ./configure"
+        echo "which is equivalent to:"
+        echo "  ./configure --with-rebar=rebar3 --disable-elixir"
+        echo "To use 'iex', recompile ejabberd enabling Elixir or using Mix:"
+        echo "  ./configure --enable-elixir"
+        echo "  ./configure --with-rebar=mix"
+        echo ""
+        exit $result
     fi
 }
 
@@ -229,15 +258,34 @@ help()
 }
 
 # dynamic node name helper
-uid()
-{
-    uuid=$(uuidgen 2>/dev/null)
-    [ -z "$uuid" ] && [ -f /proc/sys/kernel/random/uuid ] && uuid=$(cat /proc/sys/kernel/random/uuid)
-    [ -z "$uuid" ] && uuid=$(printf "%X" "${RANDOM:-$$}$(date +%M%S)")
-    uuid=$(printf '%s' $uuid | sed 's/^\(...\).*$/\1/')
-    [ $# -eq 0 ] && echo "${uuid}-${ERLANG_NODE}"
-    [ $# -eq 1 ] && echo "${uuid}-${1}-${ERLANG_NODE}"
-    [ $# -eq 2 ] && echo "${uuid}-${1}@${2}"
+uid() {
+  ERTSVERSION="$("$ERL" -version 2>&1 | sed 's|.*\([0-9][0-9]\).*|\1|g')"
+  if [ $ERTSVERSION -lt 11 ] ; then # otp 23.0 includes erts 11.0
+    # Erlang/OTP lower than 23, which doesn's support dynamic node code
+    N=1
+    PF=$(( $$ % 97 ))
+    while
+      case $# in
+        0) NN="${PF}-${N}-${ERLANG_NODE}"
+          ;;
+        1) NN="${PF}-${N}-${1}-${ERLANG_NODE}"
+          ;;
+        2) NN="${PF}-${N}-${1}@${2}"
+          ;;
+      esac
+      N=$(( N + 1 + ( $$ % 5 ) ))
+      "$EPMD" -names 2>/dev/null | grep -q " ${NN%@*} "
+    do :; done
+    echo $NN
+  else
+    # Erlang/OTP 23 or higher: use native dynamic node code
+    # https://www.erlang.org/patches/otp-23.0#OTP-13812
+    if [ "$ERLANG_NODE" != "${ERLANG_NODE%.*}" ]; then
+      echo "undefined@${ERLANG_NODE#*@}"
+    else
+      echo "undefined"
+    fi
+  fi
 }
 
 # stop epmd if there is no other running node
